baseURL: https://chapter-04-01.hugoinaction.com
languageCode: en-us
title: Acme Corporation
theme: PaperMod
enableEmoji: true
enableGitInfo: true #automatic setting for the Git author dates for the content
