baseURL: https://example.org/
languageCode: en-us
title: ACME hugo
theme: PaperMod
enableEmoji: true
author:
  facebook: "https://facebook.com/example"
  twitter: "https://twitter.com/example"

menu:
  main:
    - identifier: about
      name: About
      url: /about
      weight: 100
    - identifier: contact
      name: contact
      url: /contact
      weight: 200

